# Copyright 2026 FER, HPC Architecture and Application Research Center
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# Matej Jurasic <matej.jurasic@cappig.dev>

VERNII_SDK := ..
SOURCES    := hello.c
NAME       := hello

include $(VERNII_SDK)/vernii.mk
